### PR TITLE
Changing Kalpesh's Blog to the Insight Summer Blog

### PR DESCRIPTION
**Pull request by martiansideofthemoon**

### CODE REVIEW

**Comment by TheFlash98** [comment]
Why do you want to do this?

**Comment by martiansideofthemoon** [comment]
The insight blog is a closer description of the actual experience. The blog currently on the WnCC website was written 6 days into the internship

**Comment by martiansideofthemoon** [comment]
@TheFlash98 can we merge this?

**Comment by TheFlash98** [comment]
We can, but can we say its been adopted from your blog instead of insight?

**Comment by TheFlash98** [comment]
Realised we can't do that because http://martiansideofthemoon.github.io/2017/06/25/uchicago-4-weeks.html is empty. Merged this anyway.

**Pull request merged**
